export const allProducts = [
  {
    id: 1,
    name: "ParityKit",
    slug: "paritykit",
    tagline: "A toolkit for creating parity products",
    description:
      "ParityKit helps developers build fair and accessible pricing systems for global SaaS products with built-in A/B testing, regional adjustments, and compliance tools.",
    websiteUrl: "https://paritykit.dev",
    tags: ["SaaS", "Pricing", "Global"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 45 days ago
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "alex@indiehacker.com",
    voteCount: 120,
  },
  {
    id: 2,
    name: "Modern Full Stack Next.js Course",
    slug: "modern-full-stack-nextjs-course",
    tagline: "Learn to build production-ready full stack apps with Next.js 16",
    description:
      "Comprehensive course covering App Router, Server Components, authentication, database, deployment, and advanced patterns with real-world projects.",
    websiteUrl: "https://nextjscourse.dev",
    tags: ["Next.js", "Full-Stack", "Course"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "sarah@deveducator.com",
    voteCount: 120,
  },
  {
    id: 3,
    name: "ProofyBubble",
    slug: "proofybubble",
    tagline: "Social proof notifications that convert",
    description:
      "Real-time social proof popups, FOMO timers, recent visitor counters, and testimonial carousels that increase conversions without annoying users.",
    websiteUrl: "https://proofybubble.com",
    tags: ["Marketing", "SaaS", "Conversion"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "mike@growthhacker.io",
    voteCount: 120,
  },
  {
    id: 4,
    name: "TaskFlow Pro",
    slug: "taskflow-pro",
    tagline: "Manage projects like never before",
    description:
      "Intelligent task management with AI prioritization, automated notifications, real-time collaboration, and beautiful Kanban + list views.",
    websiteUrl: "https://taskflow.pro",
    tags: ["Productivity", "SaaS"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "emma@indiedev.com",
    voteCount: 120,
  },
  {
    id: 5,
    name: "AI Resume Builder",
    slug: "ai-resume-builder",
    tagline: "Create ATS-friendly resumes in seconds",
    description:
      "AI-powered resume generator with job description matching, keyword optimization, multiple templates, and LinkedIn integration.",
    websiteUrl: "https://airesume.build",
    tags: ["AI", "Career", "Tool"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "david@careertools.io",
    voteCount: 120,
  },
  {
    id: 6,
    name: "Notion Style CMS",
    slug: "notion-style-cms",
    tagline: "Headless CMS with Notion-like editor",
    description:
      "Beautiful block-based editor, real-time collaboration, API-first, and seamless integration with Next.js, Astro, or any frontend.",
    websiteUrl: "https://notioncms.dev",
    tags: ["CMS", "Notion", "Headless"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "julia@nocodefan.com",
    voteCount: 120,
  },
  {
    id: 7,
    name: "VibeCode",
    slug: "vibecode",
    tagline: "Code with AI that understands your vibe",
    description:
      "AI coding assistant that learns your coding style, suggests with context, refactors intelligently, and writes tests automatically.",
    websiteUrl: "https://vibecode.ai",
    tags: ["AI", "Developer Tools", "Coding"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "ryan@devtools.dev",
    voteCount: 120,
  },
  {
    id: 8,
    name: "HabitForge",
    slug: "habitforge",
    tagline: "Build unbreakable habits with science",
    description:
      "Habit tracker with streak visualization, science-based reminders, accountability partners, and AI habit coaching.",
    websiteUrl: "https://habitforge.app",
    tags: ["Productivity", "Health", "App"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "lisa@selfimprover.com",
    voteCount: 120,
  },
  {
    id: 9,
    name: "DesignVault",
    slug: "designvault",
    tagline: "Curated UI components & design systems",
    description:
      "Library of production-ready Tailwind + Shadcn UI components, design tokens, and copy-paste sections for modern web apps.",
    websiteUrl: "https://designvault.co",
    tags: ["UI", "Design", "Components"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "max@designstudio.io",
    voteCount: 120,
  },
  {
    id: 10,
    name: "LaunchList",
    slug: "launchlist",
    tagline: "Build your waitlist in minutes",
    description:
      "No-code waitlist page builder with email collection, referral system, viral loops, analytics, and Launch on Product Hunt integration.",
    websiteUrl: "https://launchlist.app",
    tags: ["SaaS", "Launch", "Marketing"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "pending" as const,
    submittedBy: "nate@indielauncher.com",
    voteCount: 120,
  },
];
